### ISSUE TITLE
Enabling cfn-hup in systemd

### ISSUE THREAD

**Issue by Mahesh81** [aws-cloudformation/aws-cloudformation-templates#227]
Hi
I tried running the following cfn to configure the cfn-hup in systemd using the following template
https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/HelperNonAmaznAmi/RHEL7_cfn-hup.template

I get the timeout error in cfn-hup.log. Any idea, what caused this issue and how to fix it
2019-10-23 16:48:09,276 [WARNING] Timeout of 60 seconds breached
2019-10-23 16:48:09,276 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)

**Comment by Mahesh81** [comment]
Hi 

Appreciate if anyone able to provide solution for this issue

Thanks
Mahesh
